#!/bin/sh
ERROR=0
oldIFS=$IFS
IFS=.
set -f
set -- $1
if [ $# -eq 4 ]; then
	for seg
	do
		case $seg in
            ""|*[!0-9]*) ERROR=1;break ;; 
            *) [ $seg -gt 255 ] && ERROR=2 ;;
        esac
    done
else
   ERROR=3
fi
IFS=$oldIFS
set +f
echo $ERROR