#!/bin/sh
kill_fw_client() {
	kfc=`ps|grep "fw_client ppp$1"|grep -v grep|awk '{print $1}'|sed -n '$p'`
	if [ ! -z ${kfc} ]; then
		kill -9 $kfc
	fi
}

kill_fw_client_wimax() {
	kfc=`ps|grep "fw_client eth$1"|grep -v grep|awk '{print $1}'|sed -n '$p'`
	if [ ! -z ${kfc} ]; then
		kill -9 $kfc
	fi
}

kill_fw_server() {
	killall fw_server
	killall fw_client
}

toggle_fw_client() {
	fs=`ps|grep "fw_server"|grep -v grep -c`                                           
	if [ $fs != 0 ]; then
		pp=`ifconfig|grep ppp$1 -c`
		fc=`ps|grep "fw_client"|grep -v grep -c`
		fc1=`ps|grep "fw_client ppp$1"|grep -v grep -c`
		
		if [ ${pp} == 1 ]; then
			mtu=`ifconfig ppp$1|grep MTU:1448 -c`
			if [ $mtu == 0 ]; then
				ifconfig ppp$1 mtu 1448
			fi
			if [ ${fc1} == 0 ]; then
				pp=`ifconfig ppp$1|sed -n '2,1p'|cut -d: -f2|awk '{print $1}'`
				fw_client ppp$1 $pp &
			fi
		else
			if [ ${fc1} == 1 ]; then
				kill_fw_client $1
			fi
		fi
	fi
}

toggle_fw_client_wimax() {
	fs=`ps|grep "fw_server"|grep -v grep -c`                                           
	if [ $fs != 0 ]; then
		eth=`ifconfig|grep eth$1 -c`
		fc=`ps|grep "fw_client eth$1"|grep -v grep -c`
		
		if [ ${eth} == 1 ]; then
			if [ ${fc} == 0 ]; then
				eth=`ifconfig eth$1|sed -n '2,1p'|cut -d: -f2|awk '{print $1}'`
				fw_client eth$1 $eth &
			fi
		else
			if [ ${fc} == 1 ]; then
				kill_fw_client_wimax $1
			fi
		fi
	fi
}

call_pppd() {
	pppd=`ps|egrep "pppd call wcdma$1.tmp|pppd call evdo$1.tmp"|grep -v "grep" -c`
	if [ $pppd == 0 ]; then
		path="/sys/devices/platform/ep93xx-ohci/usb1/1-$2"
		card=`find $path|grep ttyUSB|sort|head -n1`
		if [ -n "$card" ]; then
			l=`echo "$card"|awk '{print length($0)}'`
			min=`echo "$card"|cut -c$l-$l`
		
			product=`cat /tmp/product1-$2`
			dial_conf=`grep "$product" /etc/dial_conf`
			script=`cat /etc/ppp/standard|grep $1=|cut -d= -f2`
			tty='ttyUSB'
			offset=0
			if [ "W${product}" != "W" ] && [ "W${dial_conf}" != "W" ]; then
				tty=`echo $dial_conf|awk '{print $3}'`
				offset=`echo $dial_conf|awk '{print $4}'`
			fi
			usbno=$(expr $min '+' $offset) 
			pppd=`cat /etc/ppp/peers/$script$1|sed "s/ttyUSB.*/$tty$usbno/g" > /etc/ppp/peers/$script$1.tmp`
			kill_fw_client $1
			rm -rf /tmp/ppp*
			pppd call $script$1.tmp
		fi
	fi
}

lastppp=0
lasteth=1
ip=`ifconfig eth0|sed -n '2,1p'|cut -d: -f2|awk '{print $1}'`

start_fw_server() {
	lport=`grep local_port= /etc/mg.conf|cut -d= -f2`
	uuid=`gen_uuid`
	
	if [ ${last_type} = 1 ]; then
		tcp=" -tcp -uuid $uuid"
	else
		tcp=" -uuid $uuid"
	fi
	#. getParams
	fw_server -p $lport -d $last_port -host $last_host -l $ip -buffer $last_buffer$tcp -mode $last_trans -min $last_min -max $last_max -http $encaddr -s $last_passive & 
	echo "fw_server -p $lport -d $last_port -host $last_host -l $ip -buffer $last_buffer$tcp -mode $last_trans -min $last_min -max $last_max -http $encaddr -s $last_passive " > /tmp/fw_server 
}

kill_fw_server
last_trans=9
last_buffer=0
last_min=0
last_max=0
last_type=9
last_host=0
last_port=0
last_passive=9

rate_max=`grep rate_max= /etc/mg.conf|cut -d= -f2`
if [ "$rate_max" == "" ]; then
	rate_max="800"
fi

encaddr=`grep encaddr= /etc/mg.conf|cut -d= -f2`
if [ "$encaddr" == "" ]; then
	encaddr="192.168.1.12"
fi

encport=`cat /etc/mg.conf|grep encport=|cut -d= -f2`
if [ "$encport" == "" ]; then
	encport="6180";
fi

encoder_params $encaddr $encport 3 "enc0.vid_bitrate=${rate_max}K|"


while true; do
	killall 3gstate
	ppp=`ifconfig|grep ppp -c`
	eth=`ifconfig|grep eth -c`

	trans=`cat /etc/trans`
	passive=`cat /etc/passive`
	tcp=`grep tcp= /etc/mg.conf|cut -d= -f2`
	buffer=`grep buffer= /etc/mg.conf|cut -d= -f2`
	rate_min=`grep rate_min= /etc/mg.conf|cut -d= -f2`
	host=`grep host= /etc/mg.conf|cut -d= -f2`
	dport=`grep destination_port= /etc/mg.conf|cut -d= -f2`
	
	if [ "$passive" == "" ]; then
		passive="0"
	fi
	if [ "$rate_min" == "" ]; then
		rate_min="500"
	fi
	
	rate_max=`grep rate_max= /etc/mg.conf|cut -d= -f2`
	
	if [ "$rate_max" == "" ]; then
		rate_max="800"
	fi
	
	if [ ${ppp} != ${lastppp} ] || [ ${eth} != ${lasteth} ]; then
		lastppp=$ppp
		lasteth=$eth
		if [ $ppp == 0 ] && [ $eth == 1 ]; then
			kill_fw_server
		fi
	fi

	if [ "$last_trans" != "$trans" ] || [ "$passive" != "$last_passive" ] || [ "$tcp" != "$last_type" ] || [ "$buffer" != "$last_buffer" ] || [ "$rate_min" != "$last_min" ] || [ "$rate_max" != "$last_max" ] || [ "$host" != "$last_host" ] || [ "$dport" != "$last_port" ]; then
		last_trans=$trans
		last_passive=$passive
		last_type=$tcp
		last_buffer=$buffer
		last_min=$rate_min
		last_max=$rate_max
		last_host=$host
		last_port=$dport
		
		kill_fw_server
	fi
	
	f=`ps|grep "fw_server"|grep -v grep -c`                                           
	if ([ $ppp -gt 0 ] || [ $eth -gt 1 ]) && [ $f == 0 ]; then
		start_fw_server
	fi
	
	toggle_fw_client 0
	toggle_fw_client 1
	toggle_fw_client_wimax 1
	toggle_fw_client_wimax 2
	call_pppd 0 1
	call_pppd 1 3	
	sleep 1 
done
