#!/bin/sh
/usr/sbin/encoder_params 127.0.0.1 6180 3 "enc0.stream_url=|"
mg_conf="/etc/mg.conf"

killall_fw_server() {
	count=`ps|grep fw_server|grep -v grep -c`
	while [ $count != 0 ]; do
		pid=`ps|grep -m 1 fw_server|grep -v grep|awk '{print $1}'`
		if [ "$pid" != "" ]; then
			kill -9 $pid
		fi
		count=`ps|grep fw_server|grep -v grep -c`
	done
}

last_buffer=0
last_min=0
last_max=0
last_type=9
last_host=0
last_port=0

rate_max=`grep rate_max= /etc/mg.conf|cut -d= -f2`
if [ "$rate_max" == "" ]; then
	rate_max="800"
fi

encoder_params 127.0.0.1 6180 3 "enc0.vid_bitrate=${rate_max}K|"


start_fw_server() {
	f=`ps|grep "fw_server"|grep -v grep -c`                                                               
	while [ $f == 0 ]; do                                                               
		lport=`grep local_port= $mg_conf|cut -d= -f2`
		uuid=`gen_uuid`
		
		if [ ${last_type} = 1 ]; then
			tcp=" -tcp -uuid $uuid"
		else
			tcp=" -uuid $uuid"
		fi
		echo "fw_server -p $lport -d $last_port -host $last_host -buffer $last_buffer$tcp -mode 0 -min $last_min -max $last_max -http 127.0.0.1" > /tmp/fw_server 
		fw_server -p $lport -d $last_port -host $last_host -buffer $last_buffer$tcp -mode 0 -min $last_min -max $last_max -http 127.0.0.1 & 
		sleep 1
		f=`ps|grep "fw_server"|grep -v grep -c`
	 done
}

start_fw_client() {
	f=`ps|grep "fw_client $1 $2"|grep -v grep -c`	
	if [ $f == 0 ]; then
		killall_fw_server
		f1=`ps|grep "fw_client"|grep -v grep -c`
		if [ $f1 != 0 ]; then
			pid=`ps|grep "fw_client"|grep -v grep|awk '{print $1}'`
			kill -9 $pid	
		fi
		start_fw_server
		fw_client $1 $2 &
	fi
}

#while true; do
	tcp=`grep tcp= $mg_conf|cut -d= -f2`
	buffer=`grep buffer= $mg_conf|cut -d= -f2`
	rate_min=`grep rate_min= $mg_conf|cut -d= -f2`
	host=`grep host= $mg_conf|cut -d= -f2`
	dport=`grep destination_port= $mg_conf|cut -d= -f2`
	
	if [ "$rate_min" == "" ]; then
		rate_min="500"
	fi
	
	rate_max=`grep rate_max= /etc/mg.conf|cut -d= -f2`
	
	if [ "$rate_max" == "" ]; then
		rate_max="800"
	fi
	
	if [ "$tcp" != "$last_type" ] || [ "$buffer" != "$last_buffer" ] || [ "$rate_min" != "$last_min" ] || [ "$rate_max" != "$last_max" ] || [ "$host" != "$last_host" ] || [ "$dport" != "$last_port" ]; then
		last_type=$tcp
		last_buffer=$buffer
		last_min=$rate_min
		last_max=$rate_max
		last_host=$host
		last_port=$dport
		
		killall_fw_server
	fi

	client="ppp0"	
	ip=`ifconfig $client|sed -n '2,1p'|cut -d: -f2|awk '{print $1}'`
	start_fw_client $client $ip
		
#	sleep 10
#done
